input:
    stations: stations.csv
    ldd_fine: ../data/danube_fd.tif
    upstream_fine: ../data/ups_danube_3sec.tif
    ldd_coarse: ldd_European_01min.nc
    upstream_coarse: upArea_European_01min.nc
            
output_folder: ./shapefiles/

conditions:
    min_area: 100 # km2
    abs_error: 50 # km2
    pct_error: 1 # %