input:
    stations: stations.csv
    ldd_fine: ../data/danube_fd.tif
    upstream_fine: ../data/ups_danube_3sec.tif # MERIT Yamazaki et al 2019 
    ldd_coarse: ldd_3min.tif
    upstream_coarse: upArea_repaired.nc
            
output_folder: ./shapefiles/

conditions:
    min_area: 100 # km2
    abs_error: 50 # km2
    pct_error: 1 # %